-- 1. Tabloyu oluştur (Yoksa)
CREATE TABLE IF NOT EXISTS public.system_settings (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    telegram_bot_token TEXT,
    telegram_chat_id TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Varsayılan satırı ekle (Yoksa)
-- Bu satır olmazsa ayarlar kaydedilemez!
INSERT INTO public.system_settings (id, telegram_bot_token, telegram_chat_id)
VALUES (1, NULL, NULL)
ON CONFLICT (id) DO NOTHING;

-- 3. Yetkileri ayarla (Herkes okuyabilsin/yazabilsin - Basit Kurulum)
ALTER TABLE public.system_settings ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable read access for all users" ON public.system_settings
    FOR SELECT USING (true);

CREATE POLICY "Enable update access for all users" ON public.system_settings
    FOR UPDATE USING (true);

CREATE POLICY "Enable insert access for all users" ON public.system_settings
    FOR INSERT WITH CHECK (true);
