-- 1. Tabloyu Güvenli Şekilde Oluştur
CREATE TABLE IF NOT EXISTS public.system_settings (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    telegram_bot_token TEXT,
    telegram_chat_id TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Varsayılan Satırı Ekle (Hata vermez)
INSERT INTO public.system_settings (id, telegram_bot_token, telegram_chat_id)
VALUES (1, NULL, NULL)
ON CONFLICT (id) DO NOTHING;

-- 3. RLS Ayarlarını Düzelt (Kilit Nokta)
-- Önce RLS'yi aç, sonra herkesin erişebileceği kurallar tanımla
ALTER TABLE public.system_settings ENABLE ROW LEVEL SECURITY;

-- Eski politikaları temizle (Varsa)
DROP POLICY IF EXISTS "Enable read access for all users" ON public.system_settings;
DROP POLICY IF EXISTS "Enable update access for all users" ON public.system_settings;
DROP POLICY IF EXISTS "Enable insert access for all users" ON public.system_settings;
DROP POLICY IF EXISTS "Public Read" ON public.system_settings;
DROP POLICY IF EXISTS "Public Update" ON public.system_settings;
DROP POLICY IF EXISTS "Public Insert" ON public.system_settings;

-- Yeni "Açık Erişim" politikaları
CREATE POLICY "Public Read" ON public.system_settings FOR SELECT USING (true);
CREATE POLICY "Public Update" ON public.system_settings FOR UPDATE USING (true);
CREATE POLICY "Public Insert" ON public.system_settings FOR INSERT WITH CHECK (true);
