-- 1. Kimlik sütunu kuralını değiştir (EN ÖNEMLİ ADIM)
-- Bu komut "GENERATED ALWAYS" engelini kaldırır.
ALTER TABLE public.system_settings 
ALTER COLUMN id SET GENERATED BY DEFAULT;

-- 2. Varsayılan satırı ekle
-- Artık hata vermeden ID=1 ekleyebiliriz.
INSERT INTO public.system_settings (id, telegram_bot_token, telegram_chat_id)
VALUES (1, NULL, NULL)
ON CONFLICT (id) DO NOTHING;

-- 3. Yetkileri (RLS) Tamamen Düzelt
ALTER TABLE public.system_settings ENABLE ROW LEVEL SECURITY;

-- Eski kuralları temizle
DROP POLICY IF EXISTS "Enable read access for all users" ON public.system_settings;
DROP POLICY IF EXISTS "Enable update access for all users" ON public.system_settings;
DROP POLICY IF EXISTS "Enable insert access for all users" ON public.system_settings;
DROP POLICY IF EXISTS "Public Read" ON public.system_settings;
DROP POLICY IF EXISTS "Public Update" ON public.system_settings;
DROP POLICY IF EXISTS "Public Insert" ON public.system_settings;

-- Yeni kuralları ekle
CREATE POLICY "Public Read" ON public.system_settings FOR SELECT USING (true);
CREATE POLICY "Public Update" ON public.system_settings FOR UPDATE USING (true);
CREATE POLICY "Public Insert" ON public.system_settings FOR INSERT WITH CHECK (true);
